#!/bin/bash

docker run --rm -it \
-e APP_URI=$APP_URI \
-e MODEL_ID=$MODEL_ID \
-e NEON_DATABASE_URL=$NEON_DATABASE_URL \
-e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
-e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
-e ARTIFACT_ROOT=$ARTIFACT_ROOT \
-p 4000:4000 \
foot-predictapi:$1
